general:
  device: cpu # {cpu, cuda}
  logging-level: INFO
dataset:
  batch-size: 4
model:
  epochs: 100
  learning-rate: 0.00001
  bert:
    source: bert-base-uncased
encoder:
  bert:
    source: bert-base-uncased
    embedding-dimension: 768