general:
  device: cpu # {cpu, gpu}
  logging-level: INFO
dataset:
  batch-size: 4
  shuffle-seed: null
sentence:
  max-length: 100
model:
  epochs: 100
  learning-rate: 0.00001
  type: bert
  bert:
    source: bert-base-uncased
encoder:
  type: bert
  bert:
    source: bert-base-uncased
    embedding-dimension: 768