general:
  device: cuda # {cpu, cuda}
  logging-level: INFO
dataset:
  batch-size: 4
model:
  epochs: 100
  learning-rate: 0.00001
  early-stopping: 10 # num of epochs without improvement
  best-epoch-objective: recall # you can choose: loss and all of metrics
  bert:
    source: bert-base-uncased
  aggregators:
    endpoint:
      distance-embedding-dim: 3
  chunker:
    dice-loss-alpha: 0.0
    lambda-factor: 0.001
    loss-weight: 2.0
  triplet-extractor:
    dice-loss-alpha: 0.5
    loss-weight: 1.0
encoder:
  bert:
    source: bert-base-uncased
    embedding-dimension: 768